title: Sierra Moore
email: sierra.v.moore@gmail.com
image: "assets/img/sm.jpg"
description: "Sierra Moore Web Developer Portfolio & Resume"
keywords: "web developer, personal site, freelance web developer, front end web developer, front-end web developer, Portfolio"
#baseurl: ""
url: "https://sierramoore.github.io"
repository: https://github.com/portfolio
github_username:  sierramoore
google_analytics: UA-122925196-1

sass:
  sass_dir: _sass
  style: compressed

exclude: [".idea/", "jekyll-cache"]

# Build settings
+ markdown: CommonMark
+ commonmark:
+   options: ["SMART", "FOOTNOTES"]
+   extensions: ["strikethrough", "autolink", "table"]


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-autoprefixer
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-commonmark
  - jekyll-include-cache

#autoprefixer:
#  browsers:
#  - last 6 versions


social:
  name: Sierra Moore
  links:
    - https://www.linkedin.com/in/sierra-moore
    - https://github.com/sierramoore