title: Sierra Moore
email: sierra.v.moore@gmail.com
description: ""
#baseurl: ""
url: "https://sierramoore.github.io"
repository: https://github.com/portfolio
github_username:  sierramoore

sass:
  sass_dir: _sass
  style: compressed

exclude: [".idea/"]

# Build settings
markdown: kramdown
theme: minima


plugins:
  - jekyll-feed
  - jekyll-sitemap
#  - jekyll-autoprefixer

#autoprefixer:
#  browsers:
#  - last 6 versions